apiVersion: v1
kind: Service
metadata:
  name: alertmanager-example
spec:
  type: LoadBalancer
  ports:
  - name: web
    #  nodePort: 30903
    port: 9093
    protocol: TCP
    targetPort: web
  selector:
    alertmanager: example
