apiVersion: v1
kind: Service
metadata:
  name: java
  labels:
    release: my-prometheus-operator
  namespace: default
spec:
  ports:
  - name: web
    port: 8085
    protocol: TCP
    targetPort: 8085
  selector:
    app: java
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
