apiVersion: v1
kind: Service
metadata:
  labels:
    app: java
    release: my-prometheus-operator
  name: java-app
  namespace: monitoring
spec:
  ports:
  - name: web
    port: 8085
    protocol: TCP
    targetPort: 8085
  selector:
    app: java
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
